### ISSUE TITLE
Possible to distribute releases to Maven Central?

### ISSUE THREAD

**Issue by helpermethod** [bsideup/jabel#40]
Hi,

first of all, great project! For those of us stuck on Java 8 this library is a real godsend!

But there is still on thing which prevents me from using it in a corporate environment, and that is the use of Jitpack for distributing releases.

Is there any reason that Jabel is not distributed to Maven Central? I'm pretty sure that would greatly increase the adoption.

I would be glad to provide any help.

**Comment by bsideup** [comment]
Hi @helpermethod,

Thanks for your kind feedback! :)

You're not the first who reported troubles getting it from Jitpack. That's a shame because Jitpack is amazing, but I totally get the problem of its adoption :)

I will publish releases on Maven Central later this week, while keeping Jitpack for getting SNAPSHOTs and/or PR builds.
The progress will be reported in this issue, but expect it soon 👍

**Comment by bsideup** [comment]
FYI [the package](https://bintray.com/bsideup/releases/jabel/0.3.0) is pending an approval from Bintray to be included in JCenter and will be synced to Maven Central shortly after.

Meanwhile, it is available either via Jitpack or my Bintray repo:
```xml
    <repositories>
        <repository>
            <id>bintray-bsideup-releases</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/bsideup/releases</url>
        </repository>
    </repositories>
```

**Comment by helpermethod** [comment]
Awesome! Will give it a try this evening!

**Comment by bsideup** [comment]
The release is done and can be grabbed from Maven Central:
```xml
        <dependency>
            <groupId>com.github.bsideup.jabel</groupId>
            <artifactId>jabel-javac-plugin</artifactId>
            <version>0.3.0</version>
            <scope>provided</scope>
        </dependency>
```
