### ISSUE TITLE
--enable-preview through Jabel?

### ISSUE THREAD

**Issue by verhas** [bsideup/jabel#9]
When I use `--enable-preview` I cannot start the compilation with Jabel. It complains that Java 13 preview features are not possible to use with Java 8 release.

Could Jabel have an option so that it will also tell the compiler to handle the preview features and still generate Java 8 binary?

**Comment by bsideup** [comment]
Hi @verhas,

Please see the README, it gives an example how to integrate Jabel into your build:
https://github.com/bsideup/jabel/blob/master/README.md

When you set `release` to `8` the compiler will indeed complain that the preview features cannot be used, but you don't need to enable the flag since Jabel removes the preview flag from them.
